### ISSUE TITLE
V9 Checklist of issues

### ISSUE THREAD

**Issue by steveoh** [agrc/forklift#249]
## Ship Issues

- [x] The logs say the drop off data was copied to the servers but folders and date modified metadata is missing 24ccfcaa4c14415de07acbb0e41f4a9ca87a2a69
- [x] Pallets with `is_ready_to_ship` overrides are always shipping https://github.com/agrc/forklift/pull/259
     - [Crash](https://github.com/agrc/Crash-db/blob/master/src/CrashPallet.py)
     - [Landownership](https://github.com/agrc/warehouse/blob/master/sgid/LandOwnershipPallet.py)
	 - [ugs](https://github.com/agrc/ugs-db/blob/master/src/ugs_pallet.py)
     - [suresites](https://github.com/agrc/locate/blob/master/scripts/SureSitesPallet.py)
- [x] Shipping report was not printing in log file

## Ship Enhancements

- [x] Print packing slip to log for posterity 96daceb868c91c1037eef4e6110a0b2011609373
- [x] Add `Ship` and `Lift` to report email for search 0d50171480fedeae1ea3dea03cd4eb58ec7df77b

**Comment by steveoh** [comment]
acts had an issue with how the crates were being created. [source_primary_key](https://github.com/agrc/acts-statistics/blob/master/scripts/ActsPallet.py#L48)

Pretty sure we got rid of that... didn't we?

Parcels thought the hash location should have already been there. simple create if not exists fix...
https://github.com/agrc/Parcels/issues/47
